/* eslint-disable @typescript-eslint/naming-convention */
export enum Style {
  ClassicDashes = 'ClassicDashes',
  SparklesDesing = 'SparklesDesing',
  TrailDesign = 'TrailDesign',
  FloralDesign = 'FloralDesign',
  GalacticDesign = 'GalacticDesign',
  MinimalistDots = 'MinimalistDots',
  EmojiFun = 'EmojiFun',
  EmojiMinimalist = 'EmojiMinimalist',
  EmojiDashes = 'EmojiDashes',
  Arrows = 'Arrows',
  NestedCircles = 'NestedCircles',
  BoldBlocks = 'BoldBlocks',
  SlashSeparators = 'SlashSeparators',
  ChevronIndicators = 'ChevronIndicators',
  DotDashMix = 'DotDashMix',
  Triangles = 'Triangles',
  Zigzag = 'Zigzag',
  PipesAndHyphens = 'PipesAndHyphens',
  NestedSquares = 'NestedSquares',
  CirclesAndLines = 'CirclesAndLines',
}
